//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedKernel.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GeneralMessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralMessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharedKernel.Resources.GeneralMessageResource", typeof(GeneralMessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data was not found. Try again later..
        /// </summary>
        internal static string Error_NotFound {
            get {
                return ResourceManager.GetString("Error_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something was wrong. Try again later..
        /// </summary>
        internal static string Exception_Unexpected {
            get {
                return ResourceManager.GetString("Exception_Unexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} could not be created. Try again later..
        /// </summary>
        internal static string Exception_Unexpected_Creation_F {
            get {
                return ResourceManager.GetString("Exception_Unexpected_Creation_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} could not be created. Try again later..
        /// </summary>
        internal static string Exception_Unexpected_Creation_M {
            get {
                return ResourceManager.GetString("Exception_Unexpected_Creation_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} could not be deleted. Try again later..
        /// </summary>
        internal static string Exception_Unexpected_Deleting_F {
            get {
                return ResourceManager.GetString("Exception_Unexpected_Deleting_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} could not be deleted. Try again later..
        /// </summary>
        internal static string Exception_Unexpected_Deleting_M {
            get {
                return ResourceManager.GetString("Exception_Unexpected_Deleting_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} could not be updated. Try again later..
        /// </summary>
        internal static string Exception_Unexpected_Updating_F {
            get {
                return ResourceManager.GetString("Exception_Unexpected_Updating_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} could not be updated. Try again later..
        /// </summary>
        internal static string Exception_Unexpected_Updating_M {
            get {
                return ResourceManager.GetString("Exception_Unexpected_Updating_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists. Try to another one..
        /// </summary>
        internal static string Guard_AlreadyExists {
            get {
                return ResourceManager.GetString("Guard_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is invalid..
        /// </summary>
        internal static string Guard_InvalidFormat {
            get {
                return ResourceManager.GetString("Guard_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must have {1} or less characters..
        /// </summary>
        internal static string Guard_MaximumLenght {
            get {
                return ResourceManager.GetString("Guard_MaximumLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum value of {0} is {1}..
        /// </summary>
        internal static string Guard_MaximumValue {
            get {
                return ResourceManager.GetString("Guard_MaximumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must have {1} or more characters..
        /// </summary>
        internal static string Guard_MinimumLenght {
            get {
                return ResourceManager.GetString("Guard_MinimumLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum value of {0} is {1}..
        /// </summary>
        internal static string Guard_MinimumValue {
            get {
                return ResourceManager.GetString("Guard_MinimumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be empty. You must assign a value..
        /// </summary>
        internal static string Guard_NotNullOrEmpty {
            get {
                return ResourceManager.GetString("Guard_NotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        internal static string Middleware_ReturnException_Title {
            get {
                return ResourceManager.GetString("Middleware_ReturnException_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been created..
        /// </summary>
        internal static string Success_Creation_F {
            get {
                return ResourceManager.GetString("Success_Creation_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been created..
        /// </summary>
        internal static string Success_Creation_M {
            get {
                return ResourceManager.GetString("Success_Creation_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been deleted..
        /// </summary>
        internal static string Success_Deleting_F {
            get {
                return ResourceManager.GetString("Success_Deleting_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been deleted..
        /// </summary>
        internal static string Success_Deleting_M {
            get {
                return ResourceManager.GetString("Success_Deleting_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation was successful..
        /// </summary>
        internal static string Success_General {
            get {
                return ResourceManager.GetString("Success_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been updated..
        /// </summary>
        internal static string Success_Updating_F {
            get {
                return ResourceManager.GetString("Success_Updating_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been updated..
        /// </summary>
        internal static string Success_Updating_M {
            get {
                return ResourceManager.GetString("Success_Updating_M", resourceCulture);
            }
        }
    }
}
